name: Update Cargo dependencies
on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  cargo-update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Setup Nix
        uses: cachix/install-nix-action@v31
      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: dshuf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Perform Update
        working-directory: rust/
        run: nix develop -c cargo update
      - name: Update Nix Hashes
        run: nix develop -c nix-update dshuf-rust --version=skip --flake
      - name: Create pull request
        # FIXME: run only if there are changes
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_LABELS: dependencies,automated #${{ inputs.pr-labels }}
          AUTO_MERGE: true #${{ inputs.auto-merge }}
        run: |
          # The script should be available from the checkout
          .github/actions/create-deps-pr.sh
