name: Build & Check using Nix
on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: cachix/install-nix-action@v31
      - name: Check
        run: nix flake check
